-- AlterTable
ALTER TABLE "UserPreference" ADD COLUMN     "preferredActivityLevel" "ActivityFrequency"[] DEFAULT ARRAY[]::"ActivityFrequency"[],
ADD COLUMN     "preferredCommunication" "CommunicationStyle"[] DEFAULT ARRAY[]::"CommunicationStyle"[],
ADD COLUMN     "preferredDrinking" "DrinkingStatus"[] DEFAULT ARRAY[]::"DrinkingStatus"[],
ADD COLUMN     "preferredEducationLevels" "EducationLevel"[] DEFAULT ARRAY[]::"EducationLevel"[],
ADD COLUMN     "preferredIntentions" "Intention"[] DEFAULT ARRAY[]::"Intention"[],
ADD COLUMN     "preferredInterestsActivities" "InterestActivity"[] DEFAULT ARRAY[]::"InterestActivity"[],
ADD COLUMN     "preferredInterestsCreativity" "InterestCreativity"[] DEFAULT ARRAY[]::"InterestCreativity"[],
ADD COLUMN     "preferredInterestsLifestyle" "InterestLifestyle"[] DEFAULT ARRAY[]::"InterestLifestyle"[],
ADD COLUMN     "preferredInterestsMusic" "InterestMusic"[] DEFAULT ARRAY[]::"InterestMusic"[],
ADD COLUMN     "preferredInterestsNightlife" "InterestNightlife"[] DEFAULT ARRAY[]::"InterestNightlife"[],
ADD COLUMN     "preferredInterestsSportsFitness" "InterestSports"[] DEFAULT ARRAY[]::"InterestSports"[],
ADD COLUMN     "preferredInterestsTvCinema" "InterestTvCinema"[] DEFAULT ARRAY[]::"InterestTvCinema"[],
ADD COLUMN     "preferredLanguages" "Language"[] DEFAULT ARRAY[]::"Language"[],
ADD COLUMN     "preferredOrientations" "SexualOrientation"[] DEFAULT ARRAY[]::"SexualOrientation"[],
ADD COLUMN     "preferredPets" "PetsPreference"[] DEFAULT ARRAY[]::"PetsPreference"[],
ADD COLUMN     "preferredPronouns" "Pronoun"[] DEFAULT ARRAY[]::"Pronoun"[],
ADD COLUMN     "preferredRelationshipTypes" "RelationshipType"[] DEFAULT ARRAY[]::"RelationshipType"[],
ADD COLUMN     "preferredSmoking" "SmokingStatus"[] DEFAULT ARRAY[]::"SmokingStatus"[],
ADD COLUMN     "preferredZodiacs" "ZodiacSign"[] DEFAULT ARRAY[]::"ZodiacSign"[];
